language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
# install:
#   - pip install -r requirements.txt
before_script:
  - pip install -r tests/requirements.txt
  - git clone https://github.com/z4r/python-coveralls-example.git
  - cd python-coveralls-example
  - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
  - py.test example/tests.py --cov=example
  - cd -
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls
